package com.myspace.total_quality;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TotalQuality implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "dealPrice")
	private java.lang.Double dealPrice;
	@org.kie.api.definition.type.Label(value = "tradeAmount")
	private java.lang.Double tradeAmount;
	@org.kie.api.definition.type.Label(value = "settlementAmount")
	private java.lang.Double settlementAmount;
	@org.kie.api.definition.type.Label(value = "accuredInterest")
	private java.lang.Double accuredInterest;
	@org.kie.api.definition.type.Label(value = "accuredInterest")
	private java.lang.Double dataQualityResult;

	public TotalQuality() {
	}

	public java.lang.Double getDealPrice() {
		return this.dealPrice;
	}

	public void setDealPrice(java.lang.Double dealPrice) {
		this.dealPrice = dealPrice;
	}

	public java.lang.Double getTradeAmount() {
		return this.tradeAmount;
	}

	public void setTradeAmount(java.lang.Double tradeAmount) {
		this.tradeAmount = tradeAmount;
	}

	public java.lang.Double getSettlementAmount() {
		return this.settlementAmount;
	}

	public void setSettlementAmount(java.lang.Double settlementAmount) {
		this.settlementAmount = settlementAmount;
	}

	public java.lang.Double getAccuredInterest() {
		return this.accuredInterest;
	}

	public void setAccuredInterest(java.lang.Double accuredInterest) {
		this.accuredInterest = accuredInterest;
	}

	public java.lang.Double getDataQualityResult() {
		return this.dataQualityResult;
	}

	public void setDataQualityResult(java.lang.Double dataQualityResult) {
		this.dataQualityResult = dataQualityResult;
	}

	public TotalQuality(java.lang.Double dealPrice,
			java.lang.Double tradeAmount, java.lang.Double settlementAmount,
			java.lang.Double accuredInterest, java.lang.Double dataQualityResult) {
		this.dealPrice = dealPrice;
		this.tradeAmount = tradeAmount;
		this.settlementAmount = settlementAmount;
		this.accuredInterest = accuredInterest;
		this.dataQualityResult = dataQualityResult;
	}

}